run:
  timeout: 10m
  # Enable checking the by default skipped "examples" dirs
  skip-dirs:
    - Godeps$
    - builtin$
    - node_modules
    - testdata$
    - third_party$
    - vendor$
  skip-dirs-use-default: false
linters:
  enable-all: false
  enable:
    - errcheck
    - prealloc
    - gofumpt
    - revive
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - nakedret
    - unconvert
    - unused
    - paralleltest

linters-settings:
  nolintlint:
    # Some linter exclusions are added to generated or templated files
    # pre-emptively.
    # Don't complain about these.
    allow-unused: true

issues:
  exclude:
    # https://github.com/pulumi/pulumi/issues/9469
    - 'Name is deprecated: Name returns the variable or declaration name of the resource'

    # https://github.com/pulumi/pulumi/issues/11869
    - '"github.com/golang/protobuf/[\w/]+" is deprecated'

    # https://github.com/pulumi/pulumi/issues/11870
    - 'strings.Title has been deprecated'

    # https://github.com/pulumi/pulumi/issues/12328
    - 'deprecated: Please use types in:? cloud.google.com/go/logging/apiv2/loggingpb'